name: E2E Test

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  test:
    name: E2E DMS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: browser-actions/setup-chrome@latest
      - run: |
          npm install
          npm run cy:run